# Polynomial Time Complexity Class (P)

## Introduction

In this notebook I will be exploring the Polynomial Time Complexity Class (P). Complexity classes allow scientists to solve problems and work how many resources are required to get the solution. All these problems are broken up into different classes depending on their results, in this notebook we will look further into the class P. The class P is used for solving decision problems, these are problems that require a yes or no answer. The problems within class P are said to be 'efficiently solvable', there are exceptions to this statement both in and out of the P class, but for the majority of problems in P this is the case. [1][2]

Now that I've introduced the P class I will start looking deeper into what it is all about, here are the titles of everything I will be discussing in this notebook:
- Definition
- Notable Projects
- Polynomial Time Algorithms
- Reductions
- P versus NP Problem

## Definition

In this section I will be defining what the class P is by looking at an informal and formal characterization.

#### Informal Definition
To understand the formal definition I will first add the informal one:
- Class P consists of decision problems that can be solved using an algorithm in a certain amount of steps and set to a fixed polynomial using the input length.
- To look further at how it works we have to use a deterministic Turing Machine.
- We use Turing Machines as they are good at simulating efficient models, by squaring or cubing the computational time.
- With the class P being robust and using the same definitions as larger computer models we can easily define class P formally in terms of the Turing Machine. [3]

#### Formal Turing Machine Definition
All the elements in class P are languages. If we say Σ is a finite alphabet with at least two elements and set Σ∗ to the set of finite strings over Σ. The language that is over  Σ is a subset L of Σ∗.
So then we'll say each Turing Machine M has a related input alphabet Σ. So for each string w in Σ∗ we say a computation related to M with input w. We then say M accepts w if the computation ends in the accepted state. It can also fail if M fails to accept w by the computation ending, or if it goes into a rejected state, or the computation failing to terminate. The language that can be accepted in M, denoted L(M),  with associated alphabet Σ can be defined as follows [3]:

L(M) = {w ∈ Σ ∗ | M accepts w}.

Denoted by tM(w) is the number of steps in the computation of M on input w. If the computation never stops, then tM(w) = ∞. For n ∈ N it is denoted by TM(n) this is the worst run time case for M, defined as follows:

TM(n) = max{tM(w) | w ∈ Σ n },

where Σn is the set of all strings over Σ of length n. M runs in polynomial time if there exists k for all n, TM(n) ≤ n k + k.
Now we define the class P as follows:

P = {L | L = L(M) for some Turing machine M that runs in polynomial time}. [3]

## Notable Projects

In this section I will be looking at two of the most popular projects associated with the class P, these are the Hungarian Maximum Matching problem and AKS Primality Test. I'll do a brief overview of what they are and in the following section Polynomial Time Algorithms I will be testing the algorithms in python to see how they perform.

#### Hungarian Maximum Matching
- The Hungarian matching algorithm, also known as the Kuhn-Munkres algorithm, is an algorithm used to find maximum-weight matchings in bipartite graphs.
- It is a O(∣V∣3) algorithm.
- These graphs can easily be represented using an adjacency matrix where the weights of the edges are the entries.
- There following diagram shows the adjacency matrix representation [4]:

<img src="img/hung-match.png" align="center" width="300"/>

- The Hungarian algorithm operates on the key idea that "if a number is added or subtracted from all of the entries of any one row or column of a cost matrix, then an optimal assignment for the resulting cost matrix is also an optimal assignment for the original cost matrix"[4].
- The method works as follows:
	1. Subtract the smallest entry in each row from all the other entries in the row. Making the smallest entry in the row now equal to 0.
	2. Subtract the smallest entry in each column from all the other entries in the column. Making the smallest entry in the column now equal to 0.
	3. Draw lines through the row and columns that have the 0 entries such that the fewest lines possible are drawn.
	4. If there are n lines drawn, an optimal assignment of zeros is possible and the algorithm is finished. If the number of lines is less than n, then the optimal number of zeros is not yet reached. Go to the next step.
	5. Find the smallest entry not covered by any line. Subtract this entry from each row that isn’t crossed out, and then add it to each column that is crossed out. Then, go back to Step 3. [4]

#### Example Solution:
You are having a party and you want a musician to perform, a chef to prepare food, and a cleaning service to help clean up after the party. There are three companies that provide each of these three services, but one company can only provide one service at a time (i.e. Company A cannot provide both the cleaners and the chef). You are deciding which company you should purchase each service from in order to minimize the cost of the party. This is an assignment problem and can be graphed out of the following information [4]:

<img src="img/table.PNG" align="center" width="600"/>

Our initial matrix is the following:

<img src="img/init-mat.png" align="center" width="200"/>

Now, subtract the smallest value in each row from the other values in the row:

<img src="img/img2.png" align="center" width="200"/>

Now, subtract the smallest value in each column from all other values in the column:

<img src="img/img3.png" align="center" width="200"/>

Draw lines through the row and columns that have the 0 entries so that the fewest possible lines are drawn:

<img src="img/img4.png" align="center" width="200"/>

There are 2 lines drawn, and 2 is less than 3, so there is not yet the optimal number of zeros.
Find the smallest entry not covered by any line. Subtract this entry from each row that isn’t crossed out, and then add it to each column that is crossed out. Then, go back to Step 3.
2 is the smallest entry.
First, subtract from the uncovered rows:

<img src="img/img5.png" align="center" width="200"/>

Now add to the covered columns:

<img src="img/img 6.png" align="center" width="200"/>

Now go back to step 3, drawing lines through the rows and columns that have 0 entries:

<img src="img/img7.png" align="center" width="200"/>

There are 3 lines (which is n), so we are done. The assignment will be where the 0's are in the matrix such that only one 0 per row and column is part of the assignment.

<img src="img/img8.png" align="center" width="200"/>

Replace the original values:

<img src="img/img 9.png" align="center" width="200"/>

The Hungarian algorithm tells us that it is cheapest to go with the musician from company C, the chef from company B, and the cleaners from company A.
Verify this using brute force.
- 108 + 135 + 250 = 493
- 108 + 148 + 175 = 431
- 150 + 125 + 250 = 525
- 150 + 148 + 150 = 448
- 122 + 125 + 175 = 422
- 122 + 135 + 150 = 407.

We see that 407 is the lowest price and matches the assignment the Hungarian algorithm determined as the cheapest options. [4]

#### AKS Primality Test - Prime Test
- The next problem is  checking if a number is prime or not.
- One of the most popular tests for this is the AKS(Agrawal–Kayal–Saxena) Primality Test.
- The AKS algorithm is a deterministic primality proving algorithm and was the first one to determine in polynomial time if a number is prime or composite.
- The algorithm is 'simultaneously general, polynomial-time, deterministic, and unconditionally correct'.
- The algorithm looks like this [5]:

Input: integer n > 1.
1. Check if n is a perfect power: if n = ab for integers a > 1 and b > 1, output composite.
2. Find the smallest r such that ordr(n) > (log2 n)2. (if r and n are not coprime, then skip this r)
3. For all 2 ≤ a ≤ min (r, n−1), check that a does not divide n: If a|n for some 2 ≤ a ≤ min (r, n−1), output composite.
4. If n ≤ r, output prime.
5. For a = 1 to  do
   	if (X+a)n≠ Xn+a (mod Xr − 1,n), output composite;
6. Output prime. [5]

Explanation of Algorithm
- In step 1 we check if n is a perfect power of some integer a > 1 and the exponent b > 1. If this is the case then we output composite as n can be factored as a product of at least two factors greater than 1.
- In step 2 we find the smallest positive integer r so that the multiplication order of n modulo r (ordr(n)) is greater than (log2 n)2. This step is skipped if r and n are not coprime.
- In step 3 we check for each integer a between 2 and the minimum value of r and n-1, check if a divides into n, if it does output composite because a is a nontrivial factor of n.
- In step 4 check if n <= r and output prime as all potential prime factors of n are already found in step 3.
- In step 5 check for each integer a between 1 and X, where X is a parameter than needs to be set. Check if the equation works for some integer a, if it doesn't output composite because n is a composite number.
- In step 6 we output prime if none of the previous steps catch a composite number, this means n is prime. [5]

## Polynomial Time Algorithms

#### Hungarian Algorithm Implementation in Python [6]

In this example I will show you how to use the Hungarian algorithm to solve a linear assignment problem and find the minimum number of combinations in the matrix. This Hungarian algorithm can also be used to find the maximum combination.

In [37]:
import numpy as np

In [38]:
def min_zero_row(zero_mat, mark_zero):
    # Initialize the minimum row with a high value of 99999 and -1 index.
    min_row = [99999, -1]

    # Iterate over all rows in the matrix.
    for row in range(zero_mat.shape[0]):
        # Check if the current row contains at least one True value and has fewer True values than the current minimum row.
        if 0 < np.sum(zero_mat[row] == True) < min_row[0]:
            # Update the minimum row to the current row and its number of True values.
            min_row = [np.sum(zero_mat[row] == True), row]

    # Get the index of the first occurrence of True in the minimum row.
    index = np.where(zero_mat[min_row[1]] == True)[0][0]
    # Append the row and column to the list mark_zero.
    mark_zero.append((min_row[1], index))
    # Set all values in the minimum row and column to False.
    zero_mat[min_row[1], :] = False
    zero_mat[:, index] = False

In [39]:
def mark_matrix(mat):
    #Transform the matrix to boolean matrix(0 = True, others = False)
    current_mat = mat
    zero_bool_mat = (current_mat == 0) # Convert the input matrix to a Boolean matrix where 0s are marked as True and all other values as False
    zero_bool_mat_copy = zero_bool_mat.copy() # Create a copy of the Boolean matrix for later use

    #Recording possible answer positions by marked_zero
    marked_zero = [] # Create an empty list to store the positions of the marked zeros
    while True in zero_bool_mat_copy: # While there are still True values in the copy of the Boolean matrix:
        min_zero_row(zero_bool_mat_copy, marked_zero) # Call the min_zero_row function to find and mark the row and column containing the minimum number of zeros

    #Recording the row and column positions separately.
    marked_zero_row = [] # Create an empty list to store the row positions of the marked zeros
    marked_zero_col = [] # Create an empty list to store the column positions of the marked zeros
    for i in range(len(marked_zero)):
        marked_zero_row.append(marked_zero[i][0]) # Append the row position of each marked zero to the marked_zero_row list
        marked_zero_col.append(marked_zero[i][1]) # Append the column position of each marked zero to the marked_zero_col list

    non_marked_row = list(set(range(current_mat.shape[0])) - set(marked_zero_row)) # Create a list of row positions that were not marked

    marked_cols = [] # Create an empty list to store the column positions that are marked
    check_switch = True
    while check_switch:
        check_switch = False
        for i in range(len(non_marked_row)):
            row_array = zero_bool_mat[non_marked_row[i], :]
            for j in range(row_array.shape[0]):
                if row_array[j] == True and j not in marked_cols:
                    marked_cols.append(j)
                    check_switch = True

        for row_num, col_num in marked_zero:
            if row_num not in non_marked_row and col_num in marked_cols:
                non_marked_row.append(row_num)
                check_switch = True

    marked_rows = list(set(range(mat.shape[0])) - set(non_marked_row)) # Create a list of row positions that are marked

    # Return the positions of the marked zeros, marked rows, and marked columns.
    return marked_zero, marked_rows, marked_cols

In [40]:
def adjust_matrix(mat, cover_rows, cover_cols):
    # Make a copy of the matrix to work with
    curr_matrix = mat

    # Collect all non-covered elements in a list
    non_zero_element = []
    for row in range(len(curr_matrix)):
        if row not in cover_rows:
            for i in range(len(curr_matrix[row])):
                if i not in cover_cols:
                    non_zero_element.append(curr_matrix[row][i])

    # Find the minimum value among non-covered elements
    min_num = min(non_zero_element)

    # Subtract the minimum value from all non-covered elements
    for row in range(len(curr_matrix)):
        if row not in cover_rows:
            for i in range(len(curr_matrix[row])):
                if i not in cover_cols:
                    curr_matrix[row, i] = curr_matrix[row, i] - min_num

    # Add the minimum value to all covered elements
    for row in range(len(cover_rows)):
        for col in range(len(cover_cols)):
            curr_matrix[cover_rows[row], cover_cols[col]] = curr_matrix[cover_rows[row], cover_cols[col]] + min_num

    # Return the adjusted matrix
    return curr_matrix

In [41]:
def hungarian_algorithm(mat):
    ans_pos = 0  # Initialize the variable to store the answer position
    dim = mat.shape[0]  # Get the dimensions of the matrix
    curr_matrix = mat  # Create a copy of the input matrix

    # Every column and every row subtract its internal minimum
    for row_num in range(mat.shape[0]):
        curr_matrix[row_num] = curr_matrix[row_num] - np.min(curr_matrix[row_num])
    for col_num in range(mat.shape[1]):
        curr_matrix[:,col_num] = curr_matrix[:,col_num] - np.min(curr_matrix[:,col_num])

    # Count the number of zero entries in the matrix
    zero_count = 0

    # Loop until there are no more zero entries to mark
    while zero_count < dim:
        # Find the minimum number of lines required to cover all the zero entries
        ans_pos, marked_rows, marked_cols = mark_matrix(curr_matrix)

        # Count the number of zero entries that are not covered by the lines
        zero_count = len(marked_rows) + len(marked_cols)

        # If there are still zero entries that are not covered by the lines, adjust the matrix
        if zero_count < dim:
            curr_matrix = adjust_matrix(curr_matrix, marked_rows, marked_cols)

    # Return the answer position
    return ans_pos

In [42]:
def ans_calculation(mat, pos):
    # Initialize total to zero and create a matrix of zeros with the same shape as 'mat'
    total = 0
    ans_mat = np.zeros((mat.shape[0], mat.shape[1]))

    # For each position in 'pos', add the corresponding value in 'mat' to 'total' and copy the value to 'ans_mat'
    for i in range(len(pos)):
        total += mat[pos[i][0], pos[i][1]]
        ans_mat[pos[i][0], pos[i][1]] = mat[pos[i][0], pos[i][1]]

    # Return the sum and the matrix with only the positions specified in 'pos' containing values from 'mat'
    return total, ans_mat

In [43]:
def main():
    # The matrix for which you want to find the minimum sum
    cost_matrix = np.array([[7, 6, 2, 9, 2],
                            [6, 2, 1, 3, 9],
                            [5, 6, 8, 9, 5],
                            [6, 8, 5, 8, 6],
                            [9, 5, 6, 4, 7]])

    # Get the element position using Hungarian Algorithm
    ans_pos = hungarian_algorithm(cost_matrix.copy())

    # Get the minimum or maximum value and corresponding matrix using ans_calculation function
    ans, ans_mat = ans_calculation(cost_matrix, ans_pos)

    # Show the result
    print(f"Linear Problem Minimum Result: {ans:.0f}\n{ans_mat}")

    # If you want to find the maximum value, use the code as follows:
    # Use maximum value in the cost_matrix and subtract it from the profit_matrix to get cost_matrix
    profit_matrix = np.array([[7, 6, 2, 9, 2],
                              [6, 2, 1, 3, 9],
                              [5, 6, 8, 9, 5],
                              [6, 8, 5, 8, 6],
                              [9, 5, 6, 4, 7]])
    max_value = np.max(profit_matrix)
    cost_matrix = max_value - profit_matrix
    ans_pos = hungarian_algorithm(cost_matrix.copy())

    # Get the minimum or maximum value and corresponding matrix using ans_calculation function
    ans, ans_mat = ans_calculation(profit_matrix, ans_pos)

    # Show the result
    print(f"Linear Problem Maximum Result: {ans:.0f}\n{ans_mat}")

In [44]:
# run the main script
if __name__ == '__main__':
    main()

Linear Problem Minimum Result: 18
[[0. 0. 0. 0. 2.]
 [0. 2. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 4. 0.]]
Linear Problem Maximum Result: 43
[[0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]
 [0. 0. 8. 0. 0.]
 [0. 8. 0. 0. 0.]
 [9. 0. 0. 0. 0.]]


#### AKS Primality Test Implementation in Python [7]

In this code I will be checking if a number is prime. This program demonstrates how the AKS algorithm works and doesn't implement the actual algorithm (This works only till n = 64)

In [45]:
# array used to store coefficients
coef_array = [0] * 100;

In [46]:
# function to calculate the coefficients of (x - 1)^n - (x^n - 1) with the help of Pascal's triangle
def coef_calc(n):
    coef_array[0] = 1;
    for i in range(n):
        coef_array[1 + i] = 1;
        for j in range(i, 0, -1):
            coef_array[j] = coef_array[j - 1] - coef_array[j];
        coef_array[0] = -coef_array[0];

In [47]:
# function to check whether the number is prime or not
def isPrime(n):
    # Calculating all the coefficients by the function coef and storing all the coefficients in c array
    coef_calc(n);

    # subtracting c[n] and adding c[0] by 1 as ( x - 1 )^n - ( x^n - 1), here we are subtracting c[n] by 1 and adding 1 in expression.
    coef_array[0] = coef_array[0] + 1;
    coef_array[n] = coef_array[n] - 1;

    # checking all the coefficients whether they are divisible by n or not. if n is not prime then loop breaks and (i > 0).
    i = n;
    while i > -1 and coef_array[i] % n == 0:
        i = i - 1;

    # Return true if all coefficients are divisible by n.
    return True if i < 0 else False;

In [48]:
# Driver Code
n = 31;
if isPrime(n):
    print("Prime");
else:
    print("Not Prime");

Prime


## Reductions

In this section I will be exploring the three main types of polynomial time reductions, Many-One Reductions, Truth-Table Reductions, and Turing Reductions.

What are Polynomial-Time Reductions:
- A polynomial time reduction is a way of solving a problem by using another problem.
- It does this by checking if one problem has a hypothetical subroutine solving the second problem, if it does have this the first problem can be solved by reducing it to inputs for the second problem and calling the subroutine.
- If the time required to convert the first problem to the second, and the number of times the subroutine is called are polynomial, this means the first problem is polynomial-time reducible to the second.
- This proves that the both problems are the same difficulty to solve because whenever an effective algorithm exists for the second problem, one exists for the first one too.
- This is also the same for the other way around, if no effective algorithm exists for the first, none exist for the second. [8]

Many-One Reductions [8]:
- The many-one reduction is a polynomial-time algorithm for converting inputs from one problem into inputs to another problem, so that the converted problem will have the same outputs as the original one.
- If we take two problems, problem A and problem B, we can solve the instance x of A by doing the above conversion to give us the instance y of B, this gives y as the input to the algorithm for B and giving us an output.
- This type of reduction is denoted as follows: <img src="img/many-one.PNG" align="center" width="150"/>

Truth-Table Reductions [8]:
- The truth-table reduction is a polynomial-time algorithm used for converting inputs to a problem to a fixed number of inputs for another problem, so that the outputs of the first problem can be expressed as a function for the outputs of the second problem.
- The function that maps the outputs for the second problem into the outputs of the first problem must be the same for all the inputs.
- This type of reduction is denoted as follows: <img src="img/truth.PNG" align="center" width="80"/>

Turing Reductions [8]:
- The Turing reduction is an algorithm that solves a problem using a polynomial number of calls to a subroutine for a second problem.
- This reduction is also known as the Cook reduction which is named after Stephen Cook.
- This type of reduction is denoted as follow: <img src="img/turing.PNG" align="center" width="80"/>
- The many-one reduction is related to this reduction but is more restricted.

## P versus NP Problem

Explanation of P vs NP Problem
- The P vs NP problem is one of the most famous problems within computer science that is yet to be solved.
- It is an open problem and if someone if able to solve it there is a 1,000,000 dollar prize from the Clay Mathematics Institute.
- These two categories of problems hold the majority of common problems in the complexity theory field.
- The main problem with these is if a computer that validates a solution quickly for a difficult problem can also get the solution itself.
- The solution to the P problems can be solved and validated quickly by computers.
- While solutions to NP problems are fast to validate but extremely slow to solve.
- A more formal way of describing theses problems is, P can be solved using the abstract model of deterministic Turing machines.
- These problems take a polynomial amount of space known of polynomial-space or PSPACE.
- While NP problems are solved using non-deterministic Turing machines.
- These problems are in the complexity space non-deterministic polynomial space  or NPSPACE.
- In the current status of research many believe that P probably doesn't equal NP.
- This problem is extremely important for research into the further understanding of computational complexity.
- With the idea of Quantum computers on the horizon we may see more from this problem with scientists believing that one day we may be able to reduce problems from NP to P. [9]

## References

***

## End of Notebook